CREATE TABLE IF NOT EXISTS ping_targets(
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY, 
    created_at TIMESTAMP NOT NULL DEFAULT now(), 
    updated_at TIMESTAMP NOT NULL DEFAULT now() ON UPDATE now(),
    url VARCHAR(256) NOT NULL UNIQUE,
    fails INTEGER NOT NULL DEFAULT 0,
    last_status VARCHAR(256) NOT NULL DEFAULT '',
    last_pinged_at TIMESTAMP NULL DEFAULT NULL
);